import React, { useState, useEffect } from "react";
import { Sparkles, Calendar, Users, RefreshCw, Key, ShieldCheck } from "lucide-react";
import { useAuth } from "../lib/auth.tsx";
import { motion } from "motion/react";

interface RecommendationItem {
  id: number;
  type: "event" | "club" | "course";
  title: string;
  justification: string;
}

export const AiRecommendations: React.FC = () => {
  const [recommendations, setRecommendations] = useState<RecommendationItem[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const { token, firebaseUser, loginWithGoogle } = useAuth();

  const fetchRecommendations = async () => {
    if (!token) return;
    setLoading(true);
    setError(null);
    try {
      const response = await fetch("/api/recommendations", {
        headers: {
          "Authorization": `Bearer ${token}`
        }
      });
      if (!response.ok) {
        throw new Error("Failed to load AI recommendations.");
      }
      const data = await response.json();
      setRecommendations(data);
    } catch (err: any) {
      console.error(err);
      setError(err.message || "Could not retrieve recommendations.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (token) {
      fetchRecommendations();
    }
  }, [token]);

  if (!firebaseUser) {
    return (
      <div className="p-8 text-center bg-white dark:bg-zinc-850 border border-zinc-200 dark:border-zinc-750 rounded-3xl max-w-xl mx-auto space-y-4 shadow-xl">
        <div className="w-12 h-12 bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 rounded-2xl flex items-center justify-center mx-auto">
          <Sparkles className="w-6 h-6 animate-pulse" />
        </div>
        <div className="space-y-1">
          <h4 className="font-display font-bold text-lg text-zinc-900 dark:text-white">Unlock Personalized AI Recommendations</h4>
          <p className="text-zinc-500 dark:text-zinc-400 text-xs leading-relaxed max-w-md mx-auto">
            Our Gemini AI Recommendation engine analyzes your joined student clubs, registered events, and academic schedules to suggest custom workshops and peer circles!
          </p>
        </div>
        <motion.button
          onClick={loginWithGoogle}
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
          className="inline-flex items-center gap-2 bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold px-5 py-3 rounded-xl cursor-pointer transition-all shadow-md shadow-indigo-600/10"
        >
          <Key className="w-4 h-4" />
          Sign In with Google to Start
        </motion.button>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header section with stats & controls */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div className="space-y-1">
          <div className="flex items-center gap-2 text-indigo-650 dark:text-indigo-400 text-xs font-bold font-mono">
            <Sparkles className="w-4 h-4" />
            <span>AI ENGINE POWERED BY GOOGLE GEMINI</span>
          </div>
          <h4 className="font-display font-black text-2xl text-zinc-900 dark:text-white tracking-tight">
            Tailored For You, {firebaseUser.displayName?.split(" ")[0]}
          </h4>
          <p className="text-zinc-500 dark:text-zinc-400 text-xs">
            Dynamic, contextual suggestions generated by analyzing your active student activities profile.
          </p>
        </div>

        <motion.button
          onClick={fetchRecommendations}
          disabled={loading}
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
          className="flex items-center gap-2 bg-zinc-100 dark:bg-zinc-800 hover:bg-zinc-200 dark:hover:bg-zinc-700 text-zinc-700 hover:text-zinc-950 dark:text-zinc-300 dark:hover:text-white text-xs font-bold px-4 py-2.5 border border-zinc-200 dark:border-zinc-700 rounded-xl cursor-pointer transition-all disabled:opacity-45"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${loading ? "animate-spin" : ""}`} />
          {loading ? "Re-generating..." : "Re-generate Recommendations"}
        </motion.button>
      </div>

      {loading ? (
        <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
          {[1, 2, 3].map((n) => (
            <div key={n} className="p-6 bg-zinc-50 dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-800 rounded-3xl space-y-4 animate-pulse">
              <div className="h-4 bg-zinc-200 dark:bg-zinc-700 rounded-full w-1/3"></div>
              <div className="h-6 bg-zinc-200 dark:bg-zinc-700 rounded-full w-3/4"></div>
              <div className="space-y-2 pt-2">
                <div className="h-3 bg-zinc-200 dark:bg-zinc-700 rounded-full w-full"></div>
                <div className="h-3 bg-zinc-200 dark:bg-zinc-700 rounded-full w-5/6"></div>
              </div>
            </div>
          ))}
        </div>
      ) : error ? (
        <div className="p-8 text-center bg-zinc-50 dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 rounded-3xl">
          <p className="text-zinc-500 dark:text-zinc-400 text-sm mb-3">{error}</p>
          <button
            onClick={fetchRecommendations}
            className="bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold px-4 py-2 rounded-xl"
          >
            Retry Call
          </button>
        </div>
      ) : recommendations.length === 0 ? (
        <div className="p-8 text-center bg-zinc-50 dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 rounded-3xl space-y-2">
          <p className="text-zinc-500 dark:text-zinc-400 text-sm">We don't have enough active clubs or events in your system to analyze.</p>
          <p className="text-zinc-500 dark:text-zinc-400 text-xs">Try joining a few student clubs or subscribing to classes first!</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
          {recommendations.map((rec, i) => (
            <div
              key={i}
              className="p-5 bg-gradient-to-b from-white to-zinc-50/50 dark:from-zinc-800 dark:to-zinc-900 border border-zinc-200 dark:border-zinc-700 hover:border-zinc-300 dark:hover:border-zinc-600 rounded-3xl flex flex-col justify-between gap-5 transition-all shadow-xl hover:shadow-indigo-600/[0.03]"
            >
              <div className="space-y-3">
                {/* Badge Category */}
                <div className="flex items-center justify-between">
                  <span className={`inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-[9px] uppercase font-extrabold tracking-wider border ${
                    rec.type === "club"
                      ? "bg-amber-100/30 border-amber-300 dark:bg-amber-600/20 dark:border-amber-500/30 text-amber-700 dark:text-amber-300"
                      : "bg-indigo-100/30 border-indigo-300 dark:bg-indigo-600/20 dark:border-indigo-500/30 text-indigo-700 dark:text-indigo-300"
                  }`}>
                    {rec.type === "club" ? (
                      <Users className="w-3 h-3 text-amber-600 dark:text-amber-400" />
                    ) : (
                      <Calendar className="w-3 h-3 text-indigo-600 dark:text-indigo-400" />
                    )}
                    <span>{rec.type}</span>
                  </span>

                  <span className="text-[10px] text-zinc-500 dark:text-zinc-400 font-mono font-bold">MATCH score #0{i+1}</span>
                </div>

                <h5 className="font-display font-black text-base text-zinc-900 dark:text-white leading-snug">
                  {rec.title}
                </h5>

                <div className="bg-zinc-50 dark:bg-zinc-900/60 p-3 rounded-2xl border border-zinc-200 dark:border-zinc-800/70 text-zinc-700 dark:text-zinc-300 text-xs leading-relaxed space-y-1">
                  <span className="text-[9px] font-extrabold text-indigo-600 dark:text-indigo-400 uppercase tracking-wider block">AI Justification</span>
                  <p>{rec.justification}</p>
                </div>
              </div>

              <div className="pt-2 border-t border-zinc-100 dark:border-zinc-800 flex items-center gap-1 text-[10px] font-bold text-indigo-600 dark:text-indigo-400">
                <ShieldCheck className="w-4 h-4 text-emerald-500" />
                <span>Verified Match Recommendation</span>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};
